# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: kwan.supp
email: ksuppaiboonsuk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Kwan Suppaiboonsuk
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  kwansupp
# repository: "kwansupp/kwansupp.github.io"

# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jemoji
header_pages:
  - pages/about.md
  - pages/portfolio.md
  # - pages/blog.md
  # - pages/bookshelf.md
  # - pages/questions.md


# collections settings
collections:
  projects:
    output: true
    permalink: /portfolio/projects/:name/
  studies:
    output: true
    permalink: /portfolio/studies/:name/
  sketches:
    output: true
    permalink: /portfolio/sketches/:name/
  books:
    output: true
    permalink: /books/:name/
  questions:
    output: true
    permalink: /questions/:name/

# defaults for collections
# defaults:
#   - scope:
#       path: ""
#       type: "projects"
#     values:
#       layout: "post"

include:
  - pages


google_analytics: UA-147672831-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
